# ?? HQ ???????????????????????????????????????????????
spring.datasource.hq.jdbc-url=jdbc:h2:file:./h2data/lg_hq;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.hq.driver-class-name=org.h2.Driver
spring.datasource.hq.username=sa
spring.datasource.hq.password=
spring.datasource.hq.maximum-pool-size=5


spring.datasource.hq-batch.jdbc-url=jdbc:h2:file:./h2data/lg_hq;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.hq-batch.driver-class-name=org.h2.Driver
spring.datasource.hq-batch.username=sa
spring.datasource.hq-batch.password=
spring.datasource.hq-batch.maximum-pool-size=5

# ?? KR ???????????????????????????????????????????????
spring.datasource.kr.jdbc-url=jdbc:h2:file:./h2data/lg_kr;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.kr.driver-class-name=org.h2.Driver
spring.datasource.kr.username=sa
spring.datasource.kr.password=
spring.datasource.kr.maximum-pool-size=5

spring.datasource.kr-batch.jdbc-url=jdbc:h2:file:./h2data/lg_kr;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.kr-batch.driver-class-name=org.h2.Driver
spring.datasource.kr-batch.username=sa
spring.datasource.kr-batch.password=
spring.datasource.kr-batch.maximum-pool-size=5

# ?? US ???????????????????????????????????????????????
spring.datasource.us.jdbc-url=jdbc:h2:file:./h2data/lg_us;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.us.driver-class-name=org.h2.Driver
spring.datasource.us.username=sa
spring.datasource.us.password=
spring.datasource.us.maximum-pool-size=5

spring.datasource.us-batch.jdbc-url=jdbc:h2:file:./h2data/lg_us;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.us-batch.driver-class-name=org.h2.Driver
spring.datasource.us-batch.username=sa
spring.datasource.us-batch.password=
spring.datasource.us-batch.maximum-pool-size=5

# ?? H2 ?? ??????????????????????????????????????????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ?? Spring Batch ??????????????????????????????????????
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.main.allow-bean-definition-overriding=true
batch.target-countries=KR,US
# ?? ?? ?????????????????????????????????????????????
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

# ?? MVC ??????????????????????????????????????????????
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080
logging.level.com.lg.hq=INFO

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100


# ?? ?? ?? ???? ?????????????????????????????????
slack.enabled=false
slack.webhook.url=${SLACK_WEBHOOK_URL:demo}
exim.api.key=${EXIM_API_KEY}